version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis-server
    ports:
      - "6379:6379"

  app:
    build: .
    container_name: my-node-app
    depends_on:
      - redis
    ports:
      - "5001:5000"  # Nếu app NodeJS chạy trên cổng 5000
    environment:
      - REDIS_HOST=redis-server
      - REDIS_PORT=6379
