name: Deploy to Firebase Hosting on push

on:
  push:
    branches:
      - dev_huy  # Tự động deploy khi push vào nhánh dev_huy

jobs:x
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci
        if: exists('package-lock.json')

      - name: Build project (optional)
        run: npm run build
        if: exists('package.json')

      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}"
          channelId: live
